# Generated by Django 5.0 on 2026-03-10 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_review_rating_alter_review_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalMovieStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('northamerica', 'North America'), ('southamerica', 'South America'), ('europe', 'Europe'), ('asia', 'Asia'), ('australia', 'Australia'), ('africa', 'Africa')], max_length=50)),
                ('purchase_count', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_stats', to='movies.movie')),
            ],
            options={
                'unique_together': {('movie', 'region')},
            },
        ),
    ]
